spring.application.name=search-service
spring.data.mongodb.uri=mongodb+srv://matias_admin_g7:ddsk3003g7@cluster0.dho7ckb.mongodb.net/metamapa_search?retryWrites=true&w=majority&appName=Cluster0

server.port=8082

management.endpoints.web.exposure.include=health
management.health.probes.enabled=true